# config for https://github.com/behaviorbot/welcome

newPRWelcomeComment: >
  Thanks so much for opening your first PR here!
firstPRMergeComment: >
  Congrats on merging your first pull request here! :tada: How awesome!
newIssueWelcomeComment: >
  Thanks for opening this issue, a maintainer will get back to you shortly!
