name: Comment on issues

on:
  issues:
    types: [opened]
    
jobs:
  comment:
    runs-on: ubuntu-latest
    - uses: actions/github-script@v3.1.0
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting!'
          })
  
